### ISSUE TITLE
Enable SourceLink

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.7zip#39]

**Comment by gep13** [comment]
@nils-a just to let you know, going forward, my plan is to embed the pdb into the generated nupkg, rather than have the build create a snupkg file.  I did this last night on Cake.Json:

https://github.com/cake-contrib/Cake.Json/commit/fd8fd78e7235c138927d1cea4f3e4c489a632f82

This makes it easier to enable local debugging, and also makes it easier to debug pre-release versions which are pushed to somewhere other than nuget.org.

What are your thoughts?

**Comment by nils-a** [comment]
@gep13 On some level I "do not care how it's done" - as long as the UX is cool :-) 

Embedding will enlage the nupkg which is "bad" for people who don't use the pdb. On the other hand you're right - debugging will be easier locally and on pre-releases.

I'll have a look at Cake.Json - I imagine the "normal" pdbs won't work, right?

**Comment by gep13** [comment]
Correct, normal pdb's wouldn't work, they also need to be run through SourceLink.  The process of doing it is very similar, i.e. an additional three properties added to the csproj files.

**Comment by gep13** [comment]
Yes, it will make the nupkg slightly larger, but they are portable pdb files, so they are very small.

**Comment by nils-a** [comment]
I like it. I'll re-work this package.

**Comment by gep13** [comment]
Sweet!  Thanks for doing that!
