### ISSUE TITLE
Update buildsystem to Cake.Recipe 2.0.0

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.7zip#62]
Steps should include:

- [x] Change pre-processor directive
- [x] Pin to updated version of Cake - 0.38.4
- [x] Remove input parameters which are no longer required, for example shouldRunGitVersion: true as this is now the default
- [x] Update bootstrapper to include --bootstrap command
- [x] ~Project is using an embedded icon~
- [x] Project is using a deterministic build - --target=Enable-DeterministicBuild
- [x] Rename AppVeyor default target - AppVeyor -> CI
- [x] ~Update GitVersion.yml file with the required changes for using new version of GitVersion~
- [x] ~Add CakeContrib.Guidelines Nuget Package and add PackageIcon to csproj~
- [x] ~Remove usage of nuspec file(s) for NuGet packages, instead, we will run DotNetCore-Pack~
- [x] Add shouldUseDeterministicBuilds: true parameter
- [x] Check for usage of shouldRunCodecov: true which is not required anymore - this is new default
- [x] ~Add Cake.Addin.Analyzer package~
- [x] ~Add settings.json file for VSCode~
- [x] Add dependabot config file
- [x] Add GitHub Actions
- [x] Switch to Cake.Tool rather than Cake.exe
- [x] ~Switch to not running PR's on AppVeyor~
- [x] Check for trailing spaces in the TestCoverageFilter
- [x] Ensure targeting netstandard2.0 for project and netcoreapp2.1 and netcoreapp3.1 for tests
- [x] ~Ensure AppVeyor build image is using latest~
- [x] ~Fix broken unit tests~
- [x] ~Fix dupFinderExcludePattern for multi-targetting platforms~

**Comment by gep13** [comment]
@nils-a are all of these taken from the list that we have in the Cake.Recipe issue, or have you found that you need to add others?

**Comment by nils-a** [comment]
@gep13 only copied from Cake.Recipe. Not added anything currently. (Will notify if anything new pops up :-))

But while you here.. :-)

Can you elaborate on "Switch to not running PR's on AppVeyor"? Is setting `skip_branch_with_pr: true` meant by that?

**Comment by gep13** [comment]
That would be great, thank you!

The thought process there is due to the inclusion of dependabot.  If we do this on all repositories in the Cake-Contrib organisation, and they all at the same time get a PR to update a dependency, then this is going to swamp AppVeyor, which in the free version, only allows a single build at a time.  By switching off PR's, and only allowing builds on the main branches, we can use GitHub Actions for PR's instead.

Yes, I believe that this addition would be all that is required, but perhaps @AdmiringWorm could confirm?

**Comment by nils-a** [comment]
I *think* `skip_branch_with_pr: true` will only suppress that PR are built twice. (Like: Once for the push in the branch and once for the pr.)

**Comment by AdmiringWorm** [comment]
@nils-a because of the branches whitelist, it won't be built on the dependabot branches either.
If this section in the appveyor yaml file wasn't specified: https://github.com/cake-contrib/Cake.7zip/blob/develop/.appveyor.yml#L9-L14

Then additional configurations would be needed, either to blacklist dependabot branches, or to whitelist a select few branches.

**Comment by nils-a** [comment]
@AdmiringWorm Thanks. 

So there's actually nothing to do for that step here.

**Comment by AdmiringWorm** [comment]
Correct. There is nothing additional that needs to be done for that step in this repo.
